services:
  - type: web
    name: venture
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn venture_site.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: venture_site.settings
      - key: PYTHON_VERSION
        value: 3.10
